import {
  BiSolidUser,
  MdEmail,
  MdLocationPin,
  IoMdLock,
  FaMobileAlt,
  PiPersonArmsSpreadFill,
  PiBagSimpleFill,
} from "./IconProps";

export const formFields = [
  {
    id: 1,
    name: "name",
    type: "text",
    placeholder: "Name",
    errorMessage:
      "* Username should be 3-16 characters and shouldn't include any special character!",
    label: <BiSolidUser />,
    pattern: "^[A-Za-z0-9]{3,16}$",
    required: true,
  },
  {
    id: 2,
    name: "email",
    type: "email",
    placeholder: "Email",
    errorMessage: "* It should be a valid gmail address!",
    label: <MdEmail />,
    pattern: "/^[w.-]+@gmail.com$/i",
    required: true,
  },
  {
    id: 3,
    name: "password",
    type: "password",
    placeholder: "Password",
    errorMessage:
      "* Password should be 8-20 characters and include at least 1 letter, 1 number and 1 special character!",
    label: <IoMdLock />,
    pattern:
      "^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{8,20}$",
    required: true,
  },
  {
    id: 4,
    name: "mobileNumber",
    type: "tel",
    placeholder: "Mobile Number",
    errorMessage: "* Required",
    label: <FaMobileAlt />,
    pattern: "",
    required: true,
  },
  {
    id: 5,
    name: "age",
    type: "number",
    placeholder: "Age",
    errorMessage: "* Age Should be in between 1 to 100",
    label: <PiPersonArmsSpreadFill />,
    pattern: "^(?:[1-9][0-9]?|100)$",
    required: true,
  },
  {
    id: 6,
    name: "address",
    type: "text",
    placeholder: "Address",
    errorMessage: "",
    label: <MdLocationPin />,
    pattern: "",
    required: true,
  },
  {
    id: 7,
    name: "occupation",
    type: "text",
    placeholder: "Occupation",
    errorMessage: "",
    label: <PiBagSimpleFill />,
    pattern: "",
    required: true,
  },
];
