import {
  BiSolidUser,
  MdEmail,
  MdLocationPin,
  IoMdLock,
  FaMobileAlt,
  PiPersonArmsSpreadFill,
} from "./IconProps";

export const formFields = [
  {
    id: 1,
    name: "name",
    type: "text",
    placeholder: "Name",
    errorMessage: "",
    label: <BiSolidUser />,
    pattern: "",
    required: true,
  },
  {
    id: 2,
    name: "email",
    type: "email",
    placeholder: "Email",
    errorMessage: "",
    label: <MdEmail />,
    pattern: "",
    required: true,
  },
  {
    id: 3,
    name: "password",
    type: "password",
    placeholder: "Password",
    errorMessage: "",
    label: <IoMdLock />,
    pattern: "",
    required: true,
  },
  {
    id: 4,
    name: "mobileNumber",
    type: "tel",
    placeholder: "Mobile Number",
    errorMessage: "",
    label: <FaMobileAlt />,
    pattern: "",
    required: true,
  },
  {
    id: 5,
    name: "age",
    type: "number",
    placeholder: "Age",
    errorMessage: "",
    label: <PiPersonArmsSpreadFill />,
    pattern: "",
    required: true,
  },
  {
    id: 6,
    name: "address",
    type: "text",
    placeholder: "Address",
    errorMessage: "",
    label: <MdLocationPin />,
    pattern: "",
    required: true,
  },
  {
    id: 7,
    name: "occupation",
    type: "text",
    placeholder: "Occupation",
    errorMessage: "",
    label: <BiSolidUser />,
    pattern: "",
    required: true,
  },
];
